config/routes.rb
Rails.application.routes.draw do
  resources :bios, only: [:index, :show, :edit, :update]
  resources :authentications, only: [:destroy]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

	authenticated :user do
		root 'home#index', as: 'authenticated_root'
	end
	devise_scope :user do
		root 'devise/sessions#new'
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bio.rb
class Bio < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]
  has_one :bio
  before_create :build_default_bio

  def self.from_omniauth(auth)
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  		user.email = auth.info.email
  		user.provider = auth.provider
  		user.uid = auth.uid
  		user.password = Devise.friendly_token[0,20]
  	end
  end

  def apply_omniauth(auth)
  	update_attributes(
  		provider: auth.provider,
  		uid: auth.uid
  	)
  end

  def has_facebook_linked?
	   self.provider.present? && self.uid.present?
  end

  def bio
      super || build_bio
  end

  private

    def build_default_bio
      bio || true
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
	def destroy
		current_user.update_attributes(provider: nil, uid: nil)
		redirect_to edit_user_registration_path, notice: "Facebook Account Unlinked"
	end
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
  def index
    @bio = current_user.bio
  end

  def show
    @bio = Bio.find(params[:id])
  end

  def edit
    @bio = current_user.bio
    render layout: "first-login"
  end

  def update
    @bio = current_user.bio

    respond_to do |format|
      if @bio.update_attributes(bio_params)
        format.html { redirect_to(@bio, :notice => 'Bio was successfully updated.') }
        format.json { respond_with_bip(@bio) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@bio) }
      end
    end
  end

  private

    def bio_params
      params.require(:bio).permit(:title, :lastwords, :name, :last_name, :place_born, :place_current, :values)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
  	if current_user.present?
  		current_user.apply_omniauth(request.env["omniauth.auth"])
  		redirect_to edit_user_registration_path, notice: "Facebook Account Linked!"
  	else
  		@user = User.from_omniauth(request.env["omniauth.auth"])
  		sign_in_and_redirect @user
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/bios/edit.html.erb
<div class="container">
  <%= form_for @bio, url: {action: "update"}, html: {class: "interactive-form"} do |f| %>
  <%= f.text_field :name, :required => true, class: "interactive-input", id: "input-1"  %>
  <label for="input-1">
    <span class="label-text">First Name</span>
    <span class="nav-dot"></span>
    <div class="signup-button-trigger">Create your bio</div>
  </label>
  <%= f.text_field :last_name, :required => true,  class: "interactive-input", id: "input-2" %>
  <label for="input-2">
    <span class="label-text">Last Name</span>
    <span class="nav-dot"></span>
  </label>
  <%= f.text_field :place_born, :required => true,  class: "interactive-input", id: "input-3" %>
  <label for="input-3">
    <span class="label-text">Place I was born</span>
    <span class="nav-dot"></span>
  </label>
  <%= f.text_field :place_current, :required => true,  class: "interactive-input", id: "input-4" %>
  <label for="input-4">
    <span class="label-text">Where I live now</span>
    <span class="nav-dot"></span>
  </label>
  <%= f.text_field :values, :required => true,  class: "interactive-input", id: "input-5" %>
  <label for="input-5">
    <span class="label-text">My 3 most important values</span>
    <span class="nav-dot"></span>
  </label>
  <%= f.text_field :lastwords, :required => true,  class: "interactive-input", id: "input-6" %>
  <label for="input-6">
    <span class="label-text">My last words to humanity</span>
    <span class="nav-dot"></span>
  </label>
  <%= f.submit "go", class: "interactive-button" %>
  <p class="tip">Press Tab</p>
  <div class="signup-button">Create your bio</div>
  <% end %>
</div>

app/views/bios/index.html.erb
<div class="container">
  <div class="">
    <h1 class="bold-poppins py-1"><%= best_in_place @bio, :title %></h1>
  </div>
  <div class="row">
    <div class="col-lg-4 col-sm-12 border">
        <%= image_tag("sample.jpg", class: "img-fluid") %>
      <div class="d-flex">
        <h3 class="bold-poppins"><%= best_in_place @bio, :name %></h3>
      </div>
    </div>
    <div class="col-lg-8 border">
      <div class="row">
        <div class="col-sm-12 box-square border">
          <p class="h3 regular-poppins text-center"><%= icon('fas', 'pencil-alt') %> <%= best_in_place @bio, :lastwords %></p>
        </div>
        <div class="col-sm-12 box-square border">
          <div class="row">
            <div class="col-lg-6 col-sm-12 border">
              <span class="light-poppins regular"><%= icon('fas', 'pencil-alt') %> Name: </span><span class="light-poppins regular"><%= best_in_place @bio, :name %></span>
              <p class="light-poppins"><%= icon('fas', 'birthday-cake') %> Birthday: <%= best_in_place @bio, :birthday, :as => :date %></p>
              <p class="light-poppins"><%= icon('fas', 'leaf') %> Place born: <%= best_in_place @bio, :place_born %></p>
            </div>
            <div class="col-lg-6 col-sm-12 border">

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="container-fluid">
  <div class="card border-primary mb-3" style="max-width: 18rem;">
    <div class="card-header bg-transparent border-primary">Header</div>
    <div class="card-body text-primary">
      <h5 class="card-title">Success card title</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    <div class="card-footer bg-transparent border-primary">Footer</div>
  </div>
  <div class="card border-primary mb-3" style="max-width: 18rem;">
    <div class="card-header bg-transparent border-primary">Header</div>
    <div class="card-body text-primary">
      <h5 class="card-title">Success card title</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    <div class="card-footer bg-transparent border-primary">Footer</div>
  </div>
  <div class="card border-primary mb-3" style="max-width: 18rem;">
    <div class="card-header bg-transparent border-primary">Header</div>
    <div class="card-body text-primary">
      <h5 class="card-title">Success card title</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    <div class="card-footer bg-transparent border-primary">Footer</div>
  </div>
</div>

app/views/bios/show.html.erb
<div class="container">
  <h1 class="bold-poppins text-center py-3"><%= @bio.title %></h1>

  <div class="row">
    <div class="col-lg-4">
      <h3 class="bold-poppins text-center"><%= @bio.name %></h3>
      <div class="emi-photo">
        <%= image_tag("sample.jpg", class: "img-fluid") %>
      </div>
    </div>
    <div class="col-lg-4">
      <h2 class="regulari-poppins"><%= @bio.lastwords %></h2>
    </div>
    <div class="col-lg-4">
      <h3 class="regulari-poppins">show</h3>
    </div>
  </div>
</div>

<div class="container">
  <div class="card border-primary mb-3" style="max-width: 18rem;">
    <div class="card-header bg-transparent border-primary">Header</div>
    <div class="card-body text-primary">
      <h5 class="card-title">Success card title</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    <div class="card-footer bg-transparent border-primary">Footer</div>
  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">GroupRaise Color Testing</h1>
    <p class="lead">Make landing pages look similar to your site</p>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-light">
  <div class="container py-3">
    <div class="row text-center justify-content-center">
      <ul class="list-inline">
        <li class="list-inline-item"><a href="#"><i class="fa fa-facebook fa-2x"></i></a></li>
        <li class="list-inline-item"><a href="#"><i class="fa fa-dropbox fa-2x"></i></a></li>
        <li class="list-inline-item"><a href="#"><i class="fa fa-flickr fa-2x"></i></a></li>
        <li class="list-inline-item"><a href="#"><i class="fa fa-github fa-2x"></i></a></li>
        <li class="list-inline-item"><a href="#"><i class="fa fa-linkedin fa-2x"></i></a></li>
        <li class="list-inline-item"><a href="#"><i class="fa fa-tumblr fa-2x"></i></a></li>
      </ul>
    </div>
    <div class="row text-center justify-content-center">
      <ul class="list-inline">
        <li class="list-inline-item"><a href="#">Home</a></li>
        <li class="list-inline-item"><a href="#">About</a></li>
        <li class="list-inline-item"><a href="#">Blog</a></li>
        <li class="list-inline-item"><a href="#">Gallery</a></li>
        <li class="list-inline-item"><a href="#">Contact</a></li>
      </ul>
    </div>
    <div class="text-center justify-content-center">
     	<p class="thin-poppins small">Copyright © 2018 All rights reserved</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <!-- Sticky top not working with <header> -->
  <nav class="navbar navbar-expand-lg sticky-top bg-white border-bottom">
    <a class="navbar-brand" href="/">
      <%= image_tag("emitime_logo.png", :class => "d-inline-block align-top nav-logo") %>

      <!-- <img src="/images/emitime_logo.png" width="40" height="40" class="d-inline-block align-top" alt=""> -->
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item small"><%= link_to "First login", edit_bio_path(current_user.bio), class: "nav-link" %></li>
          <li class="nav-item small"><%= link_to "Your Bio", bios_path, method: :get, class: "nav-link" %></li>
          <li class="nav-item small"><%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item small"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link"  %></li>
        <% else %>
          <li class="nav-item small"><%= link_to "Sign up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item small"><%= link_to "Login", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>emitime | where to be remembered</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">

  </head>
  <body>
    <%= render 'layouts/header' %>

    <% if notice || alert %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/first-login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>emitime | where to be remembered </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">

  </head>
  <body>
    <%= render 'layouts/header' %>

    <% if notice || alert %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

    <%= yield %>
  </body>
</html>